# Conecttion settings 
spark.hadoop.fs.s3a.endpoint=http://minio1:9000
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.access.key=${MINIO_ROOT_USER}
spark.hadoop.fs.s3a.secret.key=${MINIO_ROOT_PASSWORD}

# retry settings
spark.hadoop.fs.s3a.retry.limit=10
spark.hadoop.fs.s3a.attempts.maximum=10
spark.hadoop.fs.s3a.retry.interval=1s
spark.hadoop.fs.s3a.connection.timeout=5000
spark.hadoop.fs.s3a.connection.establish.timeout=5000
spark.hadoop.fs.s3a.connection.maximum=100

# Upload settings
spark.hadoop.fs.s3a.multipart.size=64M
spark.hadoop.fs.s3a.multipart.threshold=64M
spark.hadoop.fs.s3a.fast.upload=true
spark.eventLog.enabled=true
spark.eventLog.dir=file:///opt/spark/work-dir/events
spark.history.fs.logDirectory=file:///opt/spark/work-dir/events

# Ssl
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.list.version=2

# Iceberg
spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.2
# Si tu Spark es 3.4.x → usa 3.4_2.12
# Si es 3.3.x → usa 3.3_2.12
spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.lakehouse=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakehouse.type=hadoop
spark.sql.catalog.lakehouse.warehouse=s3a://bronze/warehouse
spark.sql.catalog.lakehouse.s3.path-style-access=true
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem